ignoredBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@tailwindcss/oxide'

overrides:
  prismjs@<1.30.0: '>=1.30.0'
